import { useCallback, useEffect, useMemo, useState } from 'react'
import { CalendarDays, Download, Save, Search, RotateCcw } from 'lucide-react'
import AttendanceTable from '../components/AttendanceTable'
import AttendanceBadge from '../components/AttendanceBadge'
import LoadingSpinner from '../components/LoadingSpinner'
import EmptyState from '../components/EmptyState'
import { demoRecords, demoStudents, demoSubjects } from '../lib/demoData'
import { supabase } from '../lib/supabase'
import { useAuth } from '../lib/useAuth'
import { dateToday, exportCsv } from '../lib/utils'

function readDemoRegister(){let saved;try{saved=JSON.parse(localStorage.getItem('attendance-register')||'null')}catch{saved=null}const source=saved||demoRecords;return{history:source,rows:demoStudents.filter(s=>s.section==='A').map(s=>({student_id:s.id,roll_number:s.roll_number,name:s.profiles.full_name,status:source.find(r=>r.roll===s.roll_number&&r.date===dateToday())?.status||''}))}}

export default function Attendance(){
 const {profile}=useAuth();const role=profile?.role||sessionStorage.getItem('attendance-demo-role')||'admin';const studentMode=role==='student'
 const [initialRegister]=useState(readDemoRegister)
 const [subjects,setSubjects]=useState(demoSubjects);const [students,setStudents]=useState(demoStudents);const [history,setHistory]=useState(initialRegister.history);const[subject,setSubject]=useState(demoSubjects[0].id);const[section,setSection]=useState('A');const[date,setDate]=useState(dateToday());const[session,setSession]=useState('09:00');const[rows,setRows]=useState(initialRegister.rows);const[loading,setLoading]=useState(Boolean(supabase));const[saving,setSaving]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('');const[query,setQuery]=useState('');const[historyMode,setHistoryMode]=useState(false);const[historyDate,setHistoryDate]=useState('');const[historySubject,setHistorySubject]=useState('All subjects');const[historyStatus,setHistoryStatus]=useState('All statuses');const[historySection,setHistorySection]=useState('All sections');const[classId,setClassId]=useState(null)
 const loadClass=useCallback(async(id,studentList,active,sectionValue)=>{const {data,error}=await supabase.from('attendance').select('student_id,status').eq('class_id',id);if(error)throw error;if(!active)return;setRows(studentList.filter(s=>s.section===sectionValue).map(s=>({student_id:s.id,roll_number:s.roll_number,name:s.profiles?.full_name||s.name,status:data?.find(a=>a.student_id===s.id)?.status||''})))},[])
 useEffect(()=>{if(!supabase)return undefined;let active=true;(async()=>{try{const [subRes,studRes,classRes,attendanceRes]=await Promise.all([supabase.from('subjects').select('id,name,code,branch,semester,section').order('name'),supabase.from('students').select('id,profile_id,roll_number,section,profiles(full_name)').order('roll_number'),supabase.from('classes').select('id,subject_id,section,class_date,start_time,subjects(name,code)').order('class_date',{ascending:false}),supabase.from('attendance').select('id,status,students(roll_number,profiles(full_name)),classes(class_date,section,subjects(name))').order('marked_at',{ascending:false})]);for(const result of [subRes,studRes,classRes,attendanceRes])if(result.error)throw result.error;if(!active)return;setSubjects(subRes.data||[]);setStudents((studRes.data||[]).map(s=>({...s,name:s.profiles?.full_name})));const classes=classRes.data||[];setHistory((attendanceRes.data||[]).map(item=>({id:item.id,date:item.classes?.class_date,subject:item.classes?.subjects?.name,section:item.classes?.section,student:item.students?.profiles?.full_name,roll:item.students?.roll_number,status:item.status})));if(classes.length){const first=classes[0];setClassId(first.id);setSubject(first.subject_id);setSection(first.section);setDate(first.class_date);setSession(first.start_time?.slice(0,5)||'09:00');await loadClass(first.id,studRes.data||[],active,first.section)}else setRows((studRes.data||[]).map(s=>({student_id:s.id,roll_number:s.roll_number,name:s.profiles?.full_name,status:''})));}catch(issue){if(active)setError(issue.message||'Could not load attendance data.')}finally{if(active)setLoading(false)}})();return()=>{active=false}},[loadClass])
 const selectedSubject=subjects.find(s=>s.id===subject);const sections=[...new Set(students.map(s=>s.section).filter(Boolean))];const visibleRows=rows.filter(r=>`${r.name} ${r.roll_number}`.toLowerCase().includes(query.toLowerCase()));const marked=rows.filter(r=>r.status).length
 function update(id,status){setRows(items=>items.map(r=>(r.student_id||r.id)===id?{...r,status}:r))}
 async function selectSession(){setError('');setNotice('');setLoading(true);try{if(!supabase){const classForSubject=demoSubjects.find(s=>s.id===subject);setRows(demoStudents.filter(s=>s.section===section&&(!classForSubject||s.branch===classForSubject.branch)).map(s=>({student_id:s.id,roll_number:s.roll_number,name:s.profiles.full_name,status:history.find(r=>r.roll===s.roll_number&&r.date===date&&r.subject===classForSubject?.name)?.status||''})));setClassId('demo-class');return}const {data,error}=await supabase.from('classes').select('id').eq('subject_id',subject).eq('section',section).eq('class_date',date).eq('start_time',`${session}:00`).maybeSingle();if(error)throw error;if(!data){setClassId(null);setRows(students.filter(s=>s.section===section).map(s=>({...s,status:''})));setNotice('No saved class session found. Create a class session before saving attendance.');return}setClassId(data.id);const {data:att,error:attError}=await supabase.from('attendance').select('student_id,status').eq('class_id',data.id);if(attError)throw attError;setRows(students.filter(s=>s.section===section).map(s=>({...s,status:att?.find(a=>a.student_id===s.id)?.status||''}))) }catch(issue){setError(issue.message||'Could not load this class session.')}finally{setLoading(false)}}
 function markAll(status){setRows(items=>items.map(r=>({...r,status})))}
 function reset(){setRows(items=>items.map(r=>({...r,status:''})));setNotice('Changes reset. Remember to save after marking attendance.')}
 async function save(){setSaving(true);setError('');setNotice('');try{if(rows.some(r=>!r.status))throw new Error('Mark every student present, absent, or late before saving.');if(supabase){if(!classId||classId==='demo-class')throw new Error('No database class session is selected. Add a class session first.');const payload=rows.map(r=>({class_id:classId,student_id:r.student_id,status:r.status,marked_by:profile?.id}));const {error}=await supabase.from('attendance').upsert(payload,{onConflict:'class_id,student_id'});if(error)throw error;await selectSession()}else{const subjectName=selectedSubject?.name||'Class';const next=rows.map(r=>({id:`${date}-${subject}-${r.student_id}`,date,subject:subjectName,section,student:r.name,roll:r.roll_number,status:r.status}));const old=history.filter(h=>h.date!==date||h.subject!==subjectName||h.section!==section);const combined=[...next,...old];setHistory(combined);localStorage.setItem('attendance-register',JSON.stringify(combined))}setNotice('Attendance saved successfully.')}catch(issue){setError(issue.message||'Could not save attendance.')}finally{setSaving(false)}}
 const historyRows=useMemo(()=>history.map(item=>({id:item.id,roll_number:item.roll||'',name:item.student||'',status:item.status||'unmarked',date:item.date,subject:item.subject,section:item.section})),[history])
 const ownRoll=students.find(s=>s.profile_id===profile?.id)?.roll_number||(studentMode?'CS2401':'')
 const visibleHistory=historyRows.filter(r=>(!studentMode||r.roll_number===ownRoll)&&(!historyDate||r.date===historyDate)&&(historySubject==='All subjects'||r.subject===historySubject)&&(historyStatus==='All statuses'||r.status===historyStatus)&&(historySection==='All sections'||r.section===historySection))
 return <><div className="page-heading"><div><span className="eyebrow">CLASSROOM REGISTER</span><h1>{studentMode?'My attendance':'Attendance'}</h1><p>{studentMode?'Review your attendance history and class participation.':'Select a class session and mark attendance for your students.'}</p></div>{!studentMode&&<button className="secondary-button export-button" onClick={()=>exportCsv('attendance-history.csv',historyRows.map(({date,subject,student:name,roll_number,status,section})=>({date,subject,student:name,roll_number,status,section})))}><Download size={15}/> Export CSV</button>}</div>
 {!studentMode&&<div className="attendance-tabs"><button className={!historyMode?'active':''} onClick={()=>setHistoryMode(false)}>Mark register</button><button className={historyMode?'active':''} onClick={()=>setHistoryMode(true)}>Attendance history</button></div>}
 {error&&<div className="inline-error" role="alert">{error}</div>}{notice&&<div className="inline-success">{notice}</div>}
 {!studentMode&&!historyMode&&<><section className="content-card session-card"><div className="session-heading"><span className="metric-icon blue"><CalendarDays size={17}/></span><span><b>Class session</b><small>Choose the class you want to record</small></span></div><div className="session-fields"><label>Subject<select value={subject} onChange={e=>setSubject(e.target.value)}>{subjects.map(s=><option key={s.id} value={s.id}>{s.code} · {s.name}</option>)}</select></label><label>Section<select value={section} onChange={e=>setSection(e.target.value)}>{(sections.length?sections:['A']).map(s=><option key={s}>{s}</option>)}</select></label><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Session time<input type="time" value={session} onChange={e=>setSession(e.target.value)}/></label><button className="secondary-button" onClick={selectSession} disabled={loading}>Load class</button></div></section><section className="content-card register-card"><div className="register-toolbar"><div><b>Student register</b><small>{selectedSubject?.name||'Select subject'} · Section {section} · {date}</small></div><label className="search-field"><Search size={15}/><input placeholder="Search students" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="bulk-actions"><span><b>{marked}</b> of {rows.length} marked</span><div><button onClick={()=>markAll('present')}>Mark all present</button><button onClick={()=>markAll('absent')}>Mark all absent</button><button onClick={reset}><RotateCcw size={13}/> Reset</button></div></div>{loading?<LoadingSpinner label="Loading class roster…"/>:visibleRows.length?<AttendanceTable rows={visibleRows} onStatus={update} editable/>:<EmptyState title="No students in this section" description="Choose a different section or add students to the roster."/>}<div className="attendance-savebar"><span>Changes are saved to the selected class session.</span><button className="primary-button" disabled={saving||loading||!rows.length} onClick={save}><Save size={15}/>{saving?'Saving…':'Save attendance'}</button></div></section></>}
 {(studentMode||historyMode)&&<section className="content-card history-card"><div className="history-filters"><label>Date<input type="date" value={historyDate} onChange={e=>setHistoryDate(e.target.value)}/></label><label>Subject<select value={historySubject} onChange={e=>setHistorySubject(e.target.value)}><option>All subjects</option>{subjects.map(s=><option key={s.id}>{s.name}</option>)}</select></label><label>Section<select value={historySection} onChange={e=>setHistorySection(e.target.value)}><option>All sections</option>{sections.map(s=><option key={s}>{s}</option>)}</select></label><label>Status<select value={historyStatus} onChange={e=>setHistoryStatus(e.target.value)}><option>All statuses</option><option value="present">Present</option><option value="absent">Absent</option><option value="late">Late</option></select></label></div>{loading?<LoadingSpinner/>:visibleHistory.length?<div className="responsive-table"><table><thead><tr><th>DATE</th><th>SUBJECT</th>{!studentMode&&<th>STUDENT</th>}<th>ROLL NUMBER</th><th>STATUS</th><th>SECTION</th></tr></thead><tbody>{visibleHistory.map(r=><tr key={r.id}><td>{r.date}</td><td>{r.subject}</td>{!studentMode&&<td>{r.name}</td>}<td>{r.roll_number}</td><td><AttendanceBadge status={r.status}/></td><td>{r.section}</td></tr>)}</tbody></table></div>:<EmptyState title="No attendance history found" description="Try a different date or filter, or wait for an attendance session to be saved."/>}</section>}
 </>
}
