import { useEffect, useState } from 'react'
import { Save, UserCircle } from 'lucide-react'
import { useAuth } from '../lib/useAuth'
import { supabase } from '../lib/supabase'
import LoadingSpinner from '../components/LoadingSpinner'

export default function Profile(){const{profile,user}=useAuth();const role=profile?.role||sessionStorage.getItem('attendance-demo-role')||'admin';const[details,setDetails]=useState(null);const[loading,setLoading]=useState(Boolean(supabase));const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[notice,setNotice]=useState('');const[fullName,setFullName]=useState(profile?.full_name||({admin:'Demo Admin',teacher:'Demo Teacher',student:'Aarav Sharma'}[role]));
 useEffect(()=>{if(!supabase||!profile)return;let alive=true;(async()=>{const table=role==='student'?'students':'teachers';const{data,error}=await supabase.from(table).select('*').eq('profile_id',profile.id).maybeSingle();if(!alive)return;if(error)setError(error.message);else setDetails(data);setLoading(false)})();return()=>{alive=false}},[profile,role]);
 async function save(event){event.preventDefault();setBusy(true);setError('');setNotice('');try{if(supabase){const{error}=await supabase.from('profiles').update({full_name:fullName,updated_at:new Date().toISOString()}).eq('id',user.id);if(error)throw error}setNotice(supabase?'Profile updated. Refresh the page to see the updated account name everywhere.':'Demo profile changes are for display only.')}catch(issue){setError(issue.message||'Could not update your profile.')}finally{setBusy(false)}}
 const fields=role==='student'?[['Roll number',details?.roll_number||'CS2401'],['Enrollment number',details?.enrollment_number||'NCS24A001'],['Branch',details?.branch||'Computer Science'],['Section',details?.section||'A'],['Semester',details?.semester||'3']]:role==='teacher'?[['Employee ID',details?.employee_id||'FAC-024'],['Department',details?.department||'Computer Science']]:[['Access level','Full administrator']]
 return <><div className="page-heading"><div><span className="eyebrow">ACCOUNT SETTINGS</span><h1>My profile</h1><p>Review your account information and campus details.</p></div></div>{error&&<div className="inline-error">{error}</div>}{notice&&<div className="inline-success">{notice}</div>}{loading?<LoadingSpinner label="Loading your profile…"/>:<div className="profile-layout"><section className="content-card profile-summary"><div className="profile-avatar"><UserCircle size={37}/></div><h2>{profile?.full_name||fullName}</h2><span className="role-pill">{role}</span><p>{profile?.email||`${role}@northstar.edu`}</p><div className="profile-divider"/><small>MEMBER SINCE</small><b>{profile?.created_at?new Date(profile.created_at).toLocaleDateString():'Academic year 2026–27'}</b></section><section className="content-card profile-form-card"><div className="card-heading"><div><small>PERSONAL INFORMATION</small><h2>Account details</h2></div></div><form onSubmit={save} className="profile-form"><label>Full name<input required value={fullName} onChange={e=>setFullName(e.target.value)}/></label><label>Email address<input type="email" value={profile?.email||`${role}@northstar.edu`} disabled/></label><label>Role<input value={role[0].toUpperCase()+role.slice(1)} disabled/></label>{fields.map(([label,value])=><label key={label}>{label}<input value={value} disabled/></label>)}<div className="profile-actions"><span>Email and role are managed by your campus administrator.</span><button className="primary-button" disabled={busy}><Save size={15}/>{busy?'Saving…':'Save profile'}</button></div></form></section></div>}</>
}
