import { useEffect, useMemo, useState } from 'react'
import { Plus, Search, Users } from 'lucide-react'
import StudentTable from '../components/StudentTable'
import LoadingSpinner from '../components/LoadingSpinner'
import EmptyState from '../components/EmptyState'
import ConfirmDialog from '../components/ConfirmDialog'
import { demoStudents } from '../lib/demoData'
import { supabase } from '../lib/supabase'
import { useAuth } from '../lib/useAuth'
import { calculateAttendancePercentage } from '../lib/utils'

const emptyForm={roll_number:'',enrollment_number:'',branch:'Computer Science',section:'A',semester:'3',profile_id:''}
export default function Students() {
  const {profile}=useAuth();const admin=(profile?.role||sessionStorage.getItem('attendance-demo-role'))==='admin'
  const [rows,setRows]=useState(demoStudents)
  const [loading,setLoading]=useState(Boolean(supabase))
  const [busy,setBusy]=useState(false)
  const [error,setError]=useState('')
  const [notice,setNotice]=useState('')
  const [query,setQuery]=useState('')
  const [branch,setBranch]=useState('All branches')
  const [section,setSection]=useState('All sections')
  const [modal,setModal]=useState(false)
  const [editing,setEditing]=useState(null)
  const [deleting,setDeleting]=useState(null)
  const [form,setForm]=useState(emptyForm)
  useEffect(()=>{ if(!supabase)return; let active=true; Promise.all([supabase.from('students').select('id,profile_id,roll_number,enrollment_number,branch,section,semester,profiles(full_name,email)').order('roll_number'),supabase.from('attendance').select('student_id,status')]).then(([studentResult,attendanceResult])=>{if(!active)return;const issue=studentResult.error||attendanceResult.error;if(issue)setError(issue.message);else setRows((studentResult.data||[]).map(row=>{const marks=(attendanceResult.data||[]).filter(mark=>mark.student_id===row.id);return{...row,attendance_pct:calculateAttendancePercentage(marks.filter(mark=>['present','late'].includes(mark.status)).length,marks.length)}}));setLoading(false)}).catch(issue=>{if(active){setError(issue.message||'Could not load students.');setLoading(false)}});return()=>{active=false} },[])
  const filtered=useMemo(()=>rows.filter(s=>`${s.roll_number} ${s.enrollment_number} ${s.profiles?.full_name||s.name||''} ${s.branch}`.toLowerCase().includes(query.toLowerCase())&&(branch==='All branches'||s.branch===branch)&&(section==='All sections'||s.section===section)),[rows,query,branch,section])
  function openForm(row){setEditing(row||null);setForm(row?{...emptyForm,...row,semester:String(row.semester),profile_id:row.profile_id||''}:emptyForm);setModal(true);setError('');setNotice('')}
  async function save(event){event.preventDefault();setBusy(true);setError('');try{let next={...form,semester:Number(form.semester)};if(supabase){let result=editing?await supabase.from('students').update({roll_number:next.roll_number,enrollment_number:next.enrollment_number,branch:next.branch,section:next.section,semester:next.semester}).eq('id',editing.id).select('id,profile_id,roll_number,enrollment_number,branch,section,semester,profiles(full_name,email)').single():await supabase.from('students').insert({profile_id:next.profile_id,roll_number:next.roll_number,enrollment_number:next.enrollment_number,branch:next.branch,section:next.section,semester:next.semester}).select('id,profile_id,roll_number,enrollment_number,branch,section,semester,profiles(full_name,email)').single();if(result.error)throw result.error;if(editing)setRows(items=>items.map(s=>s.id===editing.id?result.data:s));else setRows(items=>[...items,result.data])}else{let fullName=next.roll_number?`Student ${next.roll_number}`:'Student';let saved={...next,id:editing?.id||crypto.randomUUID(),profiles:editing?.profiles||{full_name:fullName,email:''},attendance_pct:editing?.attendance_pct||0};setRows(items=>editing?items.map(s=>s.id===editing.id?saved:s):[...items,saved])}setModal(false);setNotice(editing?'Student updated.':'Student added.')}catch(issue){setError(issue.message||'Could not save the student.')}finally{setBusy(false)}}
  async function remove(){if(!deleting)return;setBusy(true);setError('');try{if(supabase){const{error}=await supabase.from('students').delete().eq('id',deleting.id);if(error)throw error}setRows(items=>items.filter(s=>s.id!==deleting.id));setDeleting(null);setNotice('Student removed.')}catch(issue){setError(issue.message||'Could not delete the student.')}finally{setBusy(false)}}
  return <><div className="page-heading"><div><span className="eyebrow">CAMPUS DIRECTORY</span><h1>Students</h1><p>{admin?'Manage student records and keep your class roster up to date.':'Browse the students assigned to your classes.'}</p></div>{admin&&<button className="primary-button" onClick={()=>openForm()}><Plus size={16}/> Add student</button>}</div>{error&&<div className="inline-error" role="alert">{error}</div>}{notice&&<div className="inline-success">{notice}</div>}<section className="content-card roster-card"><div className="roster-toolbar"><div className="roster-title"><span className="metric-icon blue"><Users size={17}/></span><span><b>Student roster</b><small>{filtered.length} students shown</small></span></div><label className="search-field"><Search size={15}/><input data-page-search placeholder="Search student or roll number" value={query} onChange={e=>setQuery(e.target.value)}/></label><select value={branch} onChange={e=>setBranch(e.target.value)}><option>All branches</option>{[...new Set(rows.map(s=>s.branch))].map(item=><option key={item}>{item}</option>)}</select><select value={section} onChange={e=>setSection(e.target.value)}><option>All sections</option>{[...new Set(rows.map(s=>s.section))].map(item=><option key={item}>{item}</option>)}</select></div>{loading?<LoadingSpinner label="Loading student records…"/>:filtered.length?<StudentTable students={filtered} onEdit={admin?openForm:undefined} onDelete={admin?setDeleting:undefined}/>:<EmptyState title="No students match those filters" description="Try changing your search, or add a student to the roster."/>}</section>
  {modal&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setModal(false)}><form className="dialog-card form-dialog" onSubmit={save}><button type="button" className="modal-x" onClick={()=>setModal(false)}>×</button><span className="eyebrow">ROSTER MANAGEMENT</span><h2>{editing?'Edit student':'Add student'}</h2><p>{supabase?'The student must already have a Supabase Auth account and profile.':'Demo records are saved for this session.'}</p>{error&&<div className="form-error">{error}</div>}<div className="form-grid"><label>Roll number<input required value={form.roll_number} onChange={e=>setForm({...form,roll_number:e.target.value})}/></label><label>Enrollment number<input required value={form.enrollment_number} onChange={e=>setForm({...form,enrollment_number:e.target.value})}/></label>{supabase&&!editing&&<label className="wide-field">Existing profile ID<input required placeholder="UUID from the profiles table" value={form.profile_id} onChange={e=>setForm({...form,profile_id:e.target.value})}/></label>}<label>Branch<input required value={form.branch} onChange={e=>setForm({...form,branch:e.target.value})}/></label><label>Section<input required value={form.section} onChange={e=>setForm({...form,section:e.target.value})}/></label><label>Semester<input type="number" min="1" max="12" required value={form.semester} onChange={e=>setForm({...form,semester:e.target.value})}/></label></div><div className="dialog-actions"><button type="button" className="secondary-button" onClick={()=>setModal(false)}>Cancel</button><button className="primary-button" disabled={busy}>{busy?'Saving…':'Save student'}</button></div></form></div>}
  {deleting&&<ConfirmDialog title="Delete student?" message={`This removes ${deleting.profiles?.full_name||deleting.roll_number} from the roster. Related attendance may prevent deletion.`} onCancel={()=>setDeleting(null)} onConfirm={remove} busy={busy}/>}</>
}
