import { useEffect, useState } from 'react'
import { BookOpen, Plus } from 'lucide-react'
import SubjectCard from '../components/SubjectCard'
import LoadingSpinner from '../components/LoadingSpinner'
import EmptyState from '../components/EmptyState'
import ConfirmDialog from '../components/ConfirmDialog'
import { demoSubjects } from '../lib/demoData'
import { supabase } from '../lib/supabase'
import { useAuth } from '../lib/useAuth'

const blank={name:'',code:'',branch:'Computer Science',semester:'3',section:'A',teacher_id:''}
export default function Subjects(){
  const {profile}=useAuth();const role=profile?.role||sessionStorage.getItem('attendance-demo-role')||'admin';const admin=role==='admin'
  const[subjects,setSubjects]=useState(demoSubjects);const[loading,setLoading]=useState(Boolean(supabase));const[busy,setBusy]=useState(false);const[modal,setModal]=useState(false);const[editing,setEditing]=useState(null);const[deleting,setDeleting]=useState(null);const[form,setForm]=useState(blank);const[error,setError]=useState('');const[notice,setNotice]=useState('')
  useEffect(()=>{if(!supabase)return;let active=true;supabase.from('subjects').select('id,name,code,branch,semester,section,teacher_id,teachers(profiles(full_name))').order('code').then(({data,error})=>{if(!active)return;if(error)setError(error.message);else setSubjects(data||[]);setLoading(false)});return()=>{active=false}},[])
  function open(subject){setEditing(subject||null);setForm(subject?{...blank,...subject,semester:String(subject.semester)}:blank);setError('');setModal(true)}
  async function save(e){e.preventDefault();setBusy(true);setError('');try{const payload={name:form.name,code:form.code,branch:form.branch,semester:Number(form.semester),section:form.section,teacher_id:form.teacher_id||null};let row;if(supabase){const result=editing?await supabase.from('subjects').update(payload).eq('id',editing.id).select('id,name,code,branch,semester,section,teacher_id,teachers(profiles(full_name))').single():await supabase.from('subjects').insert(payload).select('id,name,code,branch,semester,section,teacher_id,teachers(profiles(full_name))').single();if(result.error)throw result.error;row=result.data}else row={...payload,id:editing?.id||crypto.randomUUID(),teacher:form.teacher||'Faculty member'};setSubjects(items=>editing?items.map(s=>s.id===editing.id?row:s):[...items,row]);setModal(false);setNotice(editing?'Subject updated.':'Subject created.')}catch(issue){setError(issue.message||'Could not save subject.')}finally{setBusy(false)}}
  async function remove(){if(!deleting)return;setBusy(true);try{if(supabase){const{error}=await supabase.from('subjects').delete().eq('id',deleting.id);if(error)throw error}setSubjects(items=>items.filter(s=>s.id!==deleting.id));setDeleting(null);setNotice('Subject removed.')}catch(issue){setError(issue.message||'Could not delete subject.')}finally{setBusy(false)}}
  return <><div className="page-heading"><div><span className="eyebrow">ACADEMIC CATALOGUE</span><h1>Subjects</h1><p>{admin?'Manage courses, sections and faculty assignments.':'Browse the subjects assigned to your teaching workspace.'}</p></div>{admin&&<button className="primary-button" onClick={()=>open()}><Plus size={16}/> Add subject</button>}</div>{error&&<div className="inline-error">{error}</div>}{notice&&<div className="inline-success">{notice}</div>}<div className="subject-summary"><span className="metric-icon violet"><BookOpen size={17}/></span><span><b>{subjects.length} subjects</b><small>Current semester catalogue</small></span><select><option>All semesters</option><option>Semester 3</option><option>Semester 5</option></select></div>{loading?<LoadingSpinner label="Loading subjects…"/>:subjects.length?<div className="subject-grid">{subjects.map(subject=><SubjectCard key={subject.id} subject={subject} onEdit={admin?open:undefined} onDelete={admin?setDeleting:undefined}/>)}</div>:<EmptyState title="No subjects have been added" description="Subjects assigned to your account will appear here."/>}
  {modal&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setModal(false)}><form className="dialog-card form-dialog" onSubmit={save}><button type="button" className="modal-x" onClick={()=>setModal(false)}>×</button><span className="eyebrow">ACADEMIC CATALOGUE</span><h2>{editing?'Edit subject':'Add subject'}</h2>{error&&<div className="form-error">{error}</div>}<div className="form-grid"><label>Subject name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Subject code<input required value={form.code} onChange={e=>setForm({...form,code:e.target.value.toUpperCase()})}/></label><label>Branch<input required value={form.branch} onChange={e=>setForm({...form,branch:e.target.value})}/></label><label>Semester<input type="number" required min="1" max="12" value={form.semester} onChange={e=>setForm({...form,semester:e.target.value})}/></label><label>Section<input required value={form.section} onChange={e=>setForm({...form,section:e.target.value})}/></label>{supabase&&<label>Teacher ID<input placeholder="Teacher record UUID" value={form.teacher_id} onChange={e=>setForm({...form,teacher_id:e.target.value})}/></label>}</div><div className="dialog-actions"><button type="button" className="secondary-button" onClick={()=>setModal(false)}>Cancel</button><button className="primary-button" disabled={busy}>{busy?'Saving…':'Save subject'}</button></div></form></div>}{deleting&&<ConfirmDialog title="Delete subject?" message={`Delete ${deleting.name}? Associated classes may prevent deletion.`} onCancel={()=>setDeleting(null)} onConfirm={remove} busy={busy}/>}</>
}
